[package]
name = "ucore"
description = "Library with core UE components"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["ItsEthra"]
repository = "https://github.com/ItsEthra/unreal"

[dependencies]
bitflags = "1"
