[package]
name = "ucore"
description = "Library with core UE components"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
