[package]
name = "sourcer"
description = "Crate to generate source code"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
